name: Update Docs and Release

on:
  push:
    branches:
      - main

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'

    - name: Install Dependencies
      run: npm install

    - name: Build Docs
      run: npm run docs:build

    - name: Deploy Docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/.vitepress/dist

  create-release:
    runs-on: ubuntu-latest
    needs: update-docs
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'

    - name: Install Dependencies
      run: npm install

    - name: Package Code
      run: |
        git archive --format=zip --output=release.zip HEAD
        # 或者使用 tar 打包
        # git archive --format=tar --output=release.tar HEAD
      working-directory: ./  # 根据你的项目结构调整工作目录

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Sourcecode.zip  # 或者替换成你的 tar 包路径
        asset_name: Sourcecode.zip  # 或者替换成你的 tar 包名称
        asset_content_type: application/zip
